import { Address, Cell, TupleReader, openContract, type Contract, type ContractProvider, type TupleItem } from "@ton/core";

/**
 * Get-method reads through toncenter's v3 API (`/api/v3/runGetMethod`).
 * It returns typed stack entries (including nested tuples, which Tact uses for
 * optional structs), works with a TONCENTER_API_KEY, and is used first; the
 * tonhub v4 API is a fallback because its public endpoint can answer 403.
 */
export interface V3Opts {
  network: "mainnet" | "testnet";
  apiKey?: string;
  timeoutMs?: number;
}

type V3Item = { type: string; value?: unknown };

const base = (n: V3Opts["network"]) => (n === "testnet" ? "https://testnet.toncenter.com/api/v3" : "https://toncenter.com/api/v3");

export function toV3(item: TupleItem): V3Item {
  switch (item.type) {
    case "int":
      return { type: "num", value: "0x" + item.value.toString(16) };
    case "cell":
      return { type: "cell", value: item.cell.toBoc().toString("base64") };
    case "slice":
      return { type: "slice", value: item.cell.toBoc().toString("base64") };
    case "builder":
      return { type: "cell", value: item.cell.toBoc().toString("base64") };
    default:
      throw new Error(`Unsupported get-method argument: ${item.type}`);
  }
}

/** Convert a v3 stack entry into a @ton/core TupleItem. */
export function fromV3(e: V3Item): TupleItem {
  const t = e.type.toLowerCase();
  if (t === "num" || t === "int" || t === "number") {
    const v = String(e.value);
    const neg = v.startsWith("-");
    const n = BigInt(neg ? v.slice(1) : v);
    return { type: "int", value: neg ? -n : n };
  }
  if (t === "cell") return { type: "cell", cell: Cell.fromBase64(String(e.value)) };
  if (t === "slice") return { type: "slice", cell: Cell.fromBase64(String(e.value)) };
  if (t === "builder") return { type: "builder", cell: Cell.fromBase64(String(e.value)) };
  if (t === "tuple" || t === "list") return { type: "tuple", items: ((e.value as V3Item[]) ?? []).map(fromV3) };
  if (t === "null" || t === "nan") return { type: "null" };
  throw new Error(`Unknown stack entry type: ${e.type}`);
}

export async function runGetV3(opts: V3Opts, address: Address | string, method: string, args: TupleItem[] = []): Promise<TupleReader> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), opts.timeoutMs ?? 12_000);
  try {
    const res = await fetch(`${base(opts.network)}/runGetMethod`, {
      method: "POST",
      signal: ctrl.signal,
      headers: { "content-type": "application/json", accept: "application/json", ...(opts.apiKey ? { "x-api-key": opts.apiKey } : {}) },
      body: JSON.stringify({ address: address.toString(), method, stack: args.map(toV3) }),
    });
    const body = (await res.json().catch(() => ({}))) as { exit_code?: number; stack?: V3Item[]; error?: string; detail?: string };
    if (!res.ok) throw new Error(`toncenter v3 ${res.status}${body.error || body.detail ? `: ${body.error ?? body.detail}` : ""}`);
    if (body.exit_code !== 0 && body.exit_code !== 1) throw new Error(`${method} exited with ${body.exit_code}`);
    return new TupleReader((body.stack ?? []).map(fromV3));
  } finally {
    clearTimeout(timer);
  }
}

/**
 * A read-only contract opener (like `client.open`) backed by `runner`, for
 * wrappers generated by Tact: `open(BitpadFactory.fromAddress(a)).getPair(x)`.
 */
export function readOnlyOpener(runner: (address: Address, method: string, args: TupleItem[]) => Promise<TupleReader>) {
  return {
    open<T extends Contract>(contract: T) {
      return openContract(contract, ({ address }) => {
        const provider: ContractProvider = {
          async get(name, args) {
            if (typeof name !== "string") throw new Error("Method ids aren't supported");
            return { stack: await runner(address, name, args) };
          },
          getState: () => Promise.reject(new Error("read-only provider")),
          external: () => Promise.reject(new Error("read-only provider")),
          internal: () => Promise.reject(new Error("read-only provider")),
          open: () => { throw new Error("read-only provider"); },
          getTransactions: () => Promise.reject(new Error("read-only provider")),
        } as ContractProvider;
        return provider;
      });
    },
  };
}
